CREATE TABLE IF NOT EXISTS `player` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`name` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `progress` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`level` INT(11) NOT NULL,
	`profession` VARCHAR(100) NOT NULL,
	`player_id` INT(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `item` (
	`id` VARCHAR(100) PRIMARY KEY,
	`icon` VARCHAR(100),
	`level` INT(100) NOT NULL,
	`rarity` VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS `recipe` (
	`id` VARCHAR(100) PRIMARY KEY,
	`level` INT(11) NOT NULL,
	`profession` VARCHAR(100) NOT NULL,
	`result` INT(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `material` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`recipe_id` VARCHAR(100) NOT NULL,
	`item_id` VARCHAR(100) NOT NULL,
	`quantity` INT(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `craftstep` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`recipe_id` INT(255) NOT NULL,
	`order` INT(100) NOT NULL,
	`logic_id` VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS `logic` (
	`id` VARCHAR(100) PRIMARY KEY,
	`class` VARCHAR(255) NOT NULL
);

